<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ok_1</name>
   <tag></tag>
   <elementGuidId>812b6af2-e13f-4f1e-b655-86b843ff55ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mddtp-time__ok</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='mddtp-time__ok']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e9ffe73b-c8b7-4573-933c-db8b2ddc49cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mddtp-time__ok</value>
      <webElementGuid>a7d56915-ac1c-43dc-a957-1b2745566806</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mddtp-button</value>
      <webElementGuid>d890246d-88a1-4057-99e3-ba1437c4fc6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c54a488b-f065-4eba-bf48-f1754f9dcb2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ok</value>
      <webElementGuid>8ffb6b64-e1a0-429f-8436-48305390877c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mddtp-time__ok&quot;)</value>
      <webElementGuid>7c6a33c7-e526-4d8d-ae5d-c1dc1b966182</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='mddtp-time__ok']</value>
      <webElementGuid>a08f7973-e2f5-497f-8730-2aebc47c3939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mddtp-picker__time']/div[2]/div[2]/button[2]</value>
      <webElementGuid>53c6ffbe-26c9-49a6-a3ec-d34ac76e8613</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='cancel'])[2]/following::button[1]</value>
      <webElementGuid>e65e419a-1cd5-470a-9c84-7bd7d2d44623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pm'])[1]/following::button[2]</value>
      <webElementGuid>18ea49ec-de7a-4a61-8aa8-61e4a780ede4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/button[2]</value>
      <webElementGuid>b68a9939-5086-41fa-9047-47819126c6bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'mddtp-time__ok' and @type = 'button' and (text() = 'ok' or . = 'ok')]</value>
      <webElementGuid>c8c836a4-6ecf-475f-983a-c11cdcdd4024</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
