<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Loading</name>
   <tag></tag>
   <elementGuidId>8361a944-afd1-4577-8068-ee2ac49da703</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vs4__combobox > div.vs__actions</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vs4__combobox']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>566bf337-91a3-40ab-8afe-a5ecea25c06f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vs__actions</value>
      <webElementGuid>719ca4ce-7e4a-4315-b504-83df0d630a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Loading...</value>
      <webElementGuid>3dbbc0c7-edf2-4721-b3a3-0ddb3c6d65d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vs4__combobox&quot;)/div[@class=&quot;vs__actions&quot;]</value>
      <webElementGuid>279a449f-fcd6-4324-b33f-34af216949fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d5c38c5f-d13f-42bb-89b1-e11daa15d0a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vs__actions</value>
      <webElementGuid>00159a74-19c2-43f4-832c-afd6b24ebb78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Loading...</value>
      <webElementGuid>3cb21a2b-2a5b-4522-8836-5b98926b2e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vs4__combobox&quot;)/div[@class=&quot;vs__actions&quot;]</value>
      <webElementGuid>aae92d26-1c2e-459c-bb71-527b7c9f7861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b4c8eb3b-aad1-4260-9aad-68e50c022e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vs__actions</value>
      <webElementGuid>1620792b-1afd-4bd7-aff7-a3f90fb6037a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Loading...</value>
      <webElementGuid>84f9510b-b186-45b8-a8b3-e7a3cbeab580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vs4__combobox&quot;)/div[@class=&quot;vs__actions&quot;]</value>
      <webElementGuid>c73667b5-49b0-49cd-9708-e7d64094886d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vs4__combobox']/div[2]</value>
      <webElementGuid>b88d5bfc-7848-4d5a-92ed-0197e3231903</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::div[4]</value>
      <webElementGuid>9db5178f-7bf2-4abd-a830-754c5b63c4e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub category'])[1]/following::div[4]</value>
      <webElementGuid>dee90860-d67d-425a-85d3-41a289a93e57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cars'])[2]/preceding::div[2]</value>
      <webElementGuid>e8b247b7-d95c-486f-99e0-275d25ca2d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span[2]/div/div/div[2]</value>
      <webElementGuid>2e8e96ff-f2de-4ccb-a161-f7d335aa6c6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '  Loading...' or . = '  Loading...')]</value>
      <webElementGuid>7fcd5e56-cb43-44db-ba35-a99a61f7796b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
