<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>e78748c0-8e81-468e-b7d6-5021e986add8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.badge-selected > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='lightgallery']/div/div/div/div[8]/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dbd6ad83-9a32-4a30-8788-e7f42a3a362e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://mazaady-test.s3.us-east-2.amazonaws.com/LiveBadge/design_img/j5PtYFlUrsqIekEWvgXuMIE1Y3RJN2BaUszya4Kv.jpeg</value>
      <webElementGuid>acaf1068-d3f9-4b16-9bf6-b28ea3140092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lightgallery&quot;)/div[@class=&quot;slick-slider slick-initialized&quot;]/div[@class=&quot;slick-list&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide slick-active slick-current&quot;]/div[1]/div[@class=&quot;slide lightgallery-badge&quot;]/div[@class=&quot;badge-selected&quot;]/img[1]</value>
      <webElementGuid>50e8c273-ae48-410d-b8cc-9cb7005d2126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f581e6ac-4481-4e18-94ae-c5420c5e0210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://mazaady-test.s3.us-east-2.amazonaws.com/LiveBadge/design_img/j5PtYFlUrsqIekEWvgXuMIE1Y3RJN2BaUszya4Kv.jpeg</value>
      <webElementGuid>27ef4aca-dcf4-435f-be27-09ae07c68d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lightgallery&quot;)/div[@class=&quot;slick-slider slick-initialized&quot;]/div[@class=&quot;slick-list&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide slick-active slick-current&quot;]/div[1]/div[@class=&quot;slide lightgallery-badge&quot;]/div[@class=&quot;badge-selected&quot;]/img[1]</value>
      <webElementGuid>3664974c-293b-4baa-b84a-08d46ee95c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2b132381-05dc-4d4d-b0ac-cf83458ff220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://mazaady-test.s3.us-east-2.amazonaws.com/LiveBadge/design_img/j5PtYFlUrsqIekEWvgXuMIE1Y3RJN2BaUszya4Kv.jpeg</value>
      <webElementGuid>f63740a6-f17a-44ba-b941-eb0aac89b1d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lightgallery&quot;)/div[@class=&quot;slick-slider slick-initialized&quot;]/div[@class=&quot;slick-list&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide slick-active slick-current&quot;]/div[1]/div[@class=&quot;slide lightgallery-badge&quot;]/div[@class=&quot;badge-selected&quot;]/img[1]</value>
      <webElementGuid>861656f4-a0ee-407a-9582-0f69af81f98b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lightgallery']/div/div/div/div[8]/div/div/div/img</value>
      <webElementGuid>9e6df8a2-feed-48d1-8660-fbc1c447a7e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://mazaady-test.s3.us-east-2.amazonaws.com/LiveBadge/design_img/j5PtYFlUrsqIekEWvgXuMIE1Y3RJN2BaUszya4Kv.jpeg')]</value>
      <webElementGuid>5202643c-fd77-48dd-a6d2-7a9208646f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/img</value>
      <webElementGuid>ec6d9389-36fd-49e8-afe5-cac585404f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://mazaady-test.s3.us-east-2.amazonaws.com/LiveBadge/design_img/j5PtYFlUrsqIekEWvgXuMIE1Y3RJN2BaUszya4Kv.jpeg']</value>
      <webElementGuid>4b17ce46-f899-4224-9fc4-60d0cc03f809</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
