<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__starting_bid</name>
   <tag></tag>
   <elementGuidId>543cd95f-e373-40da-b882-a157ed2f1aa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;starting_bid&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='starting_bid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e26c1c2-59ed-478c-9689-1d28009f6f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>784bf2bc-926e-46bf-8f8b-f6dc89016222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>starting_bid</value>
      <webElementGuid>559e0a58-e967-4fad-9b8b-0ec9e7723581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Starting Bid Value</value>
      <webElementGuid>7596d890-d661-4c65-9a77-3c7c3a8e4899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f527379c-1057-4715-b685-2400916a4db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step-3&quot;)/span[1]/div[@class=&quot;container form-container-group&quot;]/div[@class=&quot;row mb-2&quot;]/div[@class=&quot;col-sm-6 col-12&quot;]/span[2]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>f1c9be39-d037-480c-aed7-6032ce295521</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='starting_bid']</value>
      <webElementGuid>32154b76-daf3-457b-a072-b593571f256b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-3']/span/div/div[3]/div/span[2]/input</value>
      <webElementGuid>002521b0-e45e-446f-bf77-d43d3e42973a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span/div/div[3]/div/span[2]/input</value>
      <webElementGuid>d71cfcbf-7e0f-4424-b068-58c6ef4a5bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'starting_bid' and @placeholder = 'Starting Bid Value']</value>
      <webElementGuid>fa9bb751-1849-44e8-8e0b-7eec237008a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
