<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__date</name>
   <tag></tag>
   <elementGuidId>1e5fcc26-556d-4d80-9b7a-4615ae684b5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vue-button-to-open-date</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vue-button-to-open-date']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f6776d0f-770a-4edd-ab9d-37aa928b2aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ce579475-d097-4995-b1d3-51b898748de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>bdb79616-5fad-4483-9fc9-c65da6584906</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vue-button-to-open-date</value>
      <webElementGuid>265835ed-33f7-4648-a0d2-240c61448f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Date</value>
      <webElementGuid>dc90bed7-53fb-486d-96ac-7a8a854d4532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3ae3a9ae-0c77-45fa-bc08-cc246ee8093a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control c-datepicker-input</value>
      <webElementGuid>8c2afeeb-ebb9-41e8-941a-02290a71eb7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vue-button-to-open-date&quot;)</value>
      <webElementGuid>d2aeed92-921c-4df5-bcec-27dcce1e3391</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vue-button-to-open-date']</value>
      <webElementGuid>bd43a572-4cd2-43b0-b573-67466a9b1633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-3']/span/div/div[6]/div[2]/div/div/span/input</value>
      <webElementGuid>912315c4-72ca-41f8-9049-73f426481ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div/span/input</value>
      <webElementGuid>76f20ce7-9d35-49b4-8fc4-7142894462d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'date' and @id = 'vue-button-to-open-date' and @placeholder = 'Date']</value>
      <webElementGuid>dd0c77a4-bef8-4494-b161-45b79304f9b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
