<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Estimated Value_estimated_value</name>
   <tag></tag>
   <elementGuidId>e0460491-3da4-43fa-bdff-5a571b132b75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;estimated_value&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='estimated_value']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1df6582e-0970-4bd7-a2a4-a3959a959bcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>afd121ae-a90d-409b-b2b2-99a54d92eba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>estimated_value</value>
      <webElementGuid>ad86759c-272f-4f76-a244-4a39c9756751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Estimated Value</value>
      <webElementGuid>59c81470-301a-4b44-a7ed-2a6e713f7d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a1dd6d01-0b35-40b2-9cfd-4e1898c7ab03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step-3&quot;)/span[1]/div[@class=&quot;container form-container-group&quot;]/div[@class=&quot;row mb-2&quot;]/div[@class=&quot;col-sm-12 col-12&quot;]/span[1]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>f261b64d-861d-4ad1-b2b4-a0d3ccdb5ddb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='estimated_value']</value>
      <webElementGuid>d2317222-1fbc-4fce-bcda-6b5ec7027b6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-3']/span/div/div[4]/div/span/input</value>
      <webElementGuid>7ceb89ba-ea72-43b1-abde-327527ce22a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/span/input</value>
      <webElementGuid>0293a7eb-adca-46b2-bd20-ce063a7e467f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'estimated_value' and @placeholder = 'Estimated Value']</value>
      <webElementGuid>5f29e144-5b26-44a4-a113-ac19e51c9487</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
