<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bid Increment Value_bid_increase</name>
   <tag></tag>
   <elementGuidId>a3818f8e-7edb-42c9-8a29-4662bf9a3b4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;bid_increase&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='bid_increase']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f89c2290-7889-474a-a646-33c7c32d44b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>2d0b35da-0f6f-49b4-8f44-b021aa33d82d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bid_increase</value>
      <webElementGuid>0983057b-2130-42aa-9422-99e34a82eafb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Bid Increment Value</value>
      <webElementGuid>77bcb3d2-6b36-4dd4-8dd0-61de4c3422d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>31641d74-cd91-4987-9fd8-e87add48c59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step-3&quot;)/span[1]/div[@class=&quot;container form-container-group&quot;]/div[@class=&quot;row mb-2&quot;]/div[@class=&quot;col-sm-6 col-12&quot;]/span[1]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>962aa01a-e5f1-4ef8-93ce-df4b725345da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='bid_increase']</value>
      <webElementGuid>7e7a2463-fdd4-4a47-87e1-e0a287817287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-3']/span/div/div[3]/div[2]/span/input</value>
      <webElementGuid>6a2696e8-74fc-485c-b7f5-530ba10f5bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/span/input</value>
      <webElementGuid>ee71ac99-f3d8-4e12-9329-79b33912b335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'bid_increase' and @placeholder = 'Bid Increment Value']</value>
      <webElementGuid>06b3999c-9fe1-4f2e-abdd-ac071100efe7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
