<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__time</name>
   <tag></tag>
   <elementGuidId>608d7bef-a01c-4898-a01a-8408ea0a0ef6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vue-button-to-open-time</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vue-button-to-open-time']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>597f56e8-b751-4f88-af68-aa22f70d72ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0048cac1-12c9-4e75-83e7-4a7c0c6c81f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>time</value>
      <webElementGuid>ad72fcb7-d827-4cb8-9425-8c8ed5e6b4eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vue-button-to-open-time</value>
      <webElementGuid>6a0d6f73-48f0-438f-a315-a900b3aeec96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Time</value>
      <webElementGuid>b2efa9d9-dc61-4c31-bb9a-05b623f74bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bc7c5477-b599-420f-ade3-3a24802d461d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>44318948-891c-47ab-8928-22e34ac3aef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vue-button-to-open-time&quot;)</value>
      <webElementGuid>2777d0b0-3d20-454e-a5a9-5f5644b90b02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vue-button-to-open-time']</value>
      <webElementGuid>58b38924-0c06-45a8-9119-8e198b3ad3d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-3']/span/div/div[7]/div[2]/div/div/span/input</value>
      <webElementGuid>7f0f58aa-8519-40d2-9ce1-a58f1e8596a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/div/span/input</value>
      <webElementGuid>3d07484f-937d-466b-97e5-8e547927072e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'time' and @id = 'vue-button-to-open-time' and @placeholder = 'Time']</value>
      <webElementGuid>f4ce4a37-3a54-4dd0-9f39-125990ced57f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
