<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_We still waiting your approval on the bel_8bef39</name>
   <tag></tag>
   <elementGuidId>b6d1d3df-b927-4331-8966-94fe84589a05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#approval > div.container > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='approval']/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>5afe5088-0b84-42e2-a560-8fdc970daa5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>We still waiting your approval on the below processes to proceed with them:</value>
      <webElementGuid>48105916-8729-4243-b5b3-2a6aa4d3698c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;approval&quot;)/div[@class=&quot;container&quot;]/p[1]</value>
      <webElementGuid>c702eb11-a854-4971-8627-0de6992bbb87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='approval']/div/p</value>
      <webElementGuid>7344cf47-28df-479d-9d74-a80d51f5ab49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delay'])[2]/following::p[1]</value>
      <webElementGuid>400b5044-511e-4a76-823f-43597d37797d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[3]/preceding::p[2]</value>
      <webElementGuid>72e7cb99-6bce-4fd1-9584-8009fd424dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reschedule'])[2]/preceding::p[2]</value>
      <webElementGuid>d29741ad-c6a1-4590-ae84-dbf77b71e3d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='We still waiting your approval on the below processes to proceed with them:']/parent::*</value>
      <webElementGuid>f1b9780b-7974-44d6-a547-5c568a78260c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p</value>
      <webElementGuid>4dfae883-3875-402e-9d55-e07b996484f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'We still waiting your approval on the below processes to proceed with them:' or . = 'We still waiting your approval on the below processes to proceed with them:')]</value>
      <webElementGuid>ed70a52a-f9a2-4a88-b3e8-29a4e211adda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
