<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_UNDER APPROVAL ESTIMATION VALUE HIGH_b7c475</name>
   <tag></tag>
   <elementGuidId>a880d96d-67ba-4acd-92b3-981b8e0f978f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;selling_type&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='selling_type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>feacbb5f-1130-4917-b523-97b864b6bf4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>selling_type</value>
      <webElementGuid>19a30a83-e8e9-455e-ae52-68ba43470b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>72048023-baa0-4775-b3cd-4b323117df80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>UNDER APPROVAL ESTIMATION VALUE HIGHEST PRICE </value>
      <webElementGuid>d549c6c8-b7c4-447d-883d-c063e89d5a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step-3&quot;)/span[1]/div[@class=&quot;container form-container-group&quot;]/div[@class=&quot;row mb-2&quot;]/div[@class=&quot;col-sm-6 col-12&quot;]/span[2]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>7f0b5e26-9a9f-4265-97c3-9b3524f95266</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='selling_type']</value>
      <webElementGuid>be8e4c91-4627-4707-b3c6-39ed745efe56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-3']/span/div/div/div[3]/span[2]/select</value>
      <webElementGuid>0e27567a-9d35-4cd8-9dcd-6a901a2cf2da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[14]/following::select[1]</value>
      <webElementGuid>209055d8-0315-409b-ae04-8ca7e4ce4913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selling Type'])[1]/following::select[1]</value>
      <webElementGuid>393a8f67-c101-4c60-bdaf-6386ed91b8c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Currency'])[1]/preceding::select[1]</value>
      <webElementGuid>65f8a190-00b6-4127-8c0d-fc237c658d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[15]/preceding::select[1]</value>
      <webElementGuid>cafa5278-1813-447b-b4e7-d02e9cf1787c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/span[2]/select</value>
      <webElementGuid>34804a40-ae27-4094-bdc8-17a1d11ff986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'selling_type' and (text() = 'UNDER APPROVAL ESTIMATION VALUE HIGHEST PRICE ' or . = 'UNDER APPROVAL ESTIMATION VALUE HIGHEST PRICE ')]</value>
      <webElementGuid>537e1174-a2d2-4f38-a992-b4ff9ec071f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
