<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_18</name>
   <tag></tag>
   <elementGuidId>b8cce37f-e333-4904-b0d1-01245cb4fb6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='mddtp-date__current']/div[2]/div[2]/span[22]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e3ea5c33-61fb-48d6-9e6f-35d959a5d3a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mddtp-picker__cell</value>
      <webElementGuid>82019256-a7ff-45ce-adb0-e9d0f2c847de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>63595190-0951-4b29-a399-55cbb9bbbca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mddtp-date__current&quot;)/div[@class=&quot;mddtp-picker__grid&quot;]/div[@class=&quot;mddtp-picker__tr&quot;]/span[@class=&quot;mddtp-picker__cell&quot;]</value>
      <webElementGuid>315195bf-7fc3-44df-8967-97dab2dea866</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='mddtp-date__current']/div[2]/div[2]/span[22]</value>
      <webElementGuid>8aafc769-79b4-47ee-aedc-6a0b1cd95603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[2]/following::span[22]</value>
      <webElementGuid>4666e76b-b94b-47b8-ac59-f5e4a173537a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[2]/following::span[23]</value>
      <webElementGuid>31b75365-5b6e-4144-8cb7-36577b48cfb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='January 2023'])[1]/preceding::span[21]</value>
      <webElementGuid>9db9dd40-6ad4-4b82-b9cf-f45becc26901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Su'])[3]/preceding::span[21]</value>
      <webElementGuid>b2499e4c-38b4-4178-b9a1-cb086aabecb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div[2]/div[2]/span[22]</value>
      <webElementGuid>80149a47-de80-48e9-9c00-84f7c7ae7b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '18' or . = '18')]</value>
      <webElementGuid>f042a1c4-629f-4ee8-aec1-e630d3d71c8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
