<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span</name>
   <tag></tag>
   <elementGuidId>9a5a368f-e85c-4582-9f34-943473212bda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.input-group-addon.btn.ico-id-of-button-to-open-date > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='step-3']/span/div/div[6]/div[2]/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>393c967a-a92e-41b9-a512-ecd63be5131f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step-3&quot;)/span[1]/div[@class=&quot;container form-container-group&quot;]/div[@class=&quot;row mb-2&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;input-group&quot;]/label[@class=&quot;input-group-addon btn ico-id-of-button-to-open-date&quot;]/span[1]</value>
      <webElementGuid>34f08f01-4717-4fbd-a3e5-5f0bb948a198</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-3']/span/div/div[6]/div[2]/div/label/span</value>
      <webElementGuid>8a0f8ab9-28d5-40ae-bef6-994165bb3491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label/span</value>
      <webElementGuid>21f565ba-6163-46e6-a0d1-b612ca3a2721</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
