<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Audio_switcher</name>
   <tag></tag>
   <elementGuidId>5c1fea84-47b5-4ef9-9715-7cfd517e4393</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.switcher</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='step-3']/span/div/div[9]/span/div/label/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>33bc825b-b69e-4e8c-b664-14df89fbfeff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>switcher</value>
      <webElementGuid>3ca993af-83cf-490c-b665-fe56776f576e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step-3&quot;)/span[1]/div[@class=&quot;container form-container-group&quot;]/div[@class=&quot;row mb-2&quot;]/span[1]/div[@class=&quot;col-12&quot;]/label[@class=&quot;cl-switch cl-switch-red mt-1&quot;]/span[@class=&quot;switcher&quot;]</value>
      <webElementGuid>2442605b-9828-46c2-b95b-16d6163df446</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-3']/span/div/div[9]/span/div/label/span[2]</value>
      <webElementGuid>b835693d-576e-4417-b631-568391ab7a81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span[2]</value>
      <webElementGuid>d34ea0af-89d0-48dd-bc45-034b6e723af9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
