<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_2022</name>
   <tag></tag>
   <elementGuidId>eac0a3ce-deca-41e4-b1c1-749068862ca2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='step-2']/span/div[2]/div[4]/div/span/div[17]/div/div/div[2]/span[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>54df56b7-e29f-496e-9d8f-35073528ef48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cell year</value>
      <webElementGuid>c167c81f-8502-4903-bccc-3f0470562d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2022</value>
      <webElementGuid>bb869580-5cb9-4ee4-8a89-7accb45680b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step-2&quot;)/span[1]/div[@class=&quot;container form-container-group&quot;]/div[4]/div[1]/span[1]/div[@class=&quot;row mb-2&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;vdp-datepicker&quot;]/div[@class=&quot;vdp-datepicker__calendar&quot;]/span[@class=&quot;cell year&quot;]</value>
      <webElementGuid>82c63f6b-a2ce-40cf-94dc-a929f3b30092</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>865eb318-fc28-4632-b26b-40051ad70bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cell year</value>
      <webElementGuid>1d33f760-e8b9-48be-91ff-2569698cea22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2022</value>
      <webElementGuid>8363c7fd-a7c7-492b-9539-6532890eedd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step-2&quot;)/span[1]/div[@class=&quot;container form-container-group&quot;]/div[4]/div[1]/span[1]/div[@class=&quot;row mb-2&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;vdp-datepicker&quot;]/div[@class=&quot;vdp-datepicker__calendar&quot;]/span[@class=&quot;cell year&quot;]</value>
      <webElementGuid>1db3b9d2-5fe3-43c0-ba18-35198fe991c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>581fba5f-8e81-4dcc-a12f-11a57f9e6581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cell year</value>
      <webElementGuid>880871bf-2695-469a-8beb-0ad191a55c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2022</value>
      <webElementGuid>50453648-6c0d-4453-bb24-88d318defed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;step-2&quot;)/span[1]/div[@class=&quot;container form-container-group&quot;]/div[4]/div[1]/span[1]/div[@class=&quot;row mb-2&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;vdp-datepicker&quot;]/div[@class=&quot;vdp-datepicker__calendar&quot;]/span[@class=&quot;cell year&quot;]</value>
      <webElementGuid>9bed15b8-5c28-448b-9280-51d2105e527b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-2']/span/div[2]/div[4]/div/span/div[17]/div/div/div[2]/span[3]</value>
      <webElementGuid>93f02b89-fb0a-447d-a19c-8fbc08d76c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>'])[1]/following::span[3]</value>
      <webElementGuid>52d74779-69b6-4461-9862-7994f551149a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;'])[1]/following::span[5]</value>
      <webElementGuid>b6b6808c-acf9-4aa6-bf6a-cc3552ac6005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country Made'])[1]/preceding::span[8]</value>
      <webElementGuid>3195ddf0-fa76-4516-b9d6-6fd2fef19bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[16]/preceding::span[8]</value>
      <webElementGuid>6ca93110-5ef2-416a-b34e-4ec05e45c33b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2022']/parent::*</value>
      <webElementGuid>8ebc9854-d810-49cb-8689-1f27c6405942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/div/div[2]/span[3]</value>
      <webElementGuid>fc49695e-2d55-405d-8754-197a4d795824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '2022' or . = '2022')]</value>
      <webElementGuid>b00a1a10-2176-4c43-a53e-7d3a16ceb46a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
