<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_17</name>
   <tag></tag>
   <elementGuidId>4e82cfc8-f5fa-4d4d-b46c-da5979e98140</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mddtp-date__selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='mddtp-date__selected']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e0d34b13-ad6e-4172-a0c6-c908b0b6d8bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mddtp-picker__cell mddtp-picker__cell--today mddtp-picker__cell--selected</value>
      <webElementGuid>6d733fb6-b97f-482f-a8eb-71713c7a2a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mddtp-date__selected</value>
      <webElementGuid>db0d0103-b3ee-4540-88db-512c2a9e8b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>46d7ea46-f4c9-4597-970a-f2294cce44b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mddtp-date__selected&quot;)</value>
      <webElementGuid>6234bf95-fb4f-40a0-92b6-03cb683aa781</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='mddtp-date__selected']</value>
      <webElementGuid>af8e03ff-b8e7-4b1b-bd6b-24c8ad2074b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='mddtp-date__current']/div[2]/div[2]/span[21]</value>
      <webElementGuid>c8154ed9-41c9-4ff3-9c7a-1f24f107fe1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[2]/following::span[21]</value>
      <webElementGuid>a5b4e548-6ebe-4816-8c1b-3a92dbb2802c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fr'])[2]/following::span[22]</value>
      <webElementGuid>76bb94f1-5051-4053-9ca3-16471bdbcbd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='January 2023'])[1]/preceding::span[22]</value>
      <webElementGuid>6119d9a7-698f-4ea3-9199-fa79629542eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Su'])[3]/preceding::span[22]</value>
      <webElementGuid>a4813ac0-3f1e-44a3-8d2d-f196f165789c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div[2]/div[2]/span[21]</value>
      <webElementGuid>28a40cb0-5820-4687-be39-40c6acbdd73a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'mddtp-date__selected' and (text() = '17' or . = '17')]</value>
      <webElementGuid>5960ec5b-c1de-4277-84a0-a10bda14df23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
